name: Build All Upstream Tags

on:
  workflow_dispatch:
    inputs:
      max_tags:
        description: 'Maximum number of recent tags to build (default: 10)'
        required: false
        type: string
        default: '10'
      start_from_tag:
        description: 'Start building from this tag (optional, e.g., v6.0.0)'
        required: false
        type: string
      build_architectures:
        description: 'Architectures to build'
        required: true
        type: choice
        options:
          - both
          - x64-only
          - x86-only
        default: both
      skip_existing:
        description: 'Skip tags that already have releases'
        required: true
        type: boolean
        default: true

jobs:
  get-upstream-tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.get-tags.outputs.tags }}
      tags-count: ${{ steps.get-tags.outputs.tags-count }}
    steps:
      - name: Get upstream ReShade tags
        id: get-tags
        run: |
          # Get all tags from upstream ReShade repository
          echo "Fetching upstream tags..."
          TAGS=$(curl -s "https://api.github.com/repos/crosire/reshade/tags?per_page=100" | jq -r '.[].name' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V)

          # If start_from_tag is specified, filter from that tag onwards
          if [ -n "${{ github.event.inputs.start_from_tag }}" ]; then
            echo "Filtering from tag: ${{ github.event.inputs.start_from_tag }}"
            TAGS=$(echo "$TAGS" | awk -v start="${{ github.event.inputs.start_from_tag }}" 'BEGIN{found=0} {if($0==start) found=1; if(found) print}')
          fi

          # Limit to max_tags
          MAX_TAGS="${{ github.event.inputs.max_tags }}"
          TAGS=$(echo "$TAGS" | tail -n $MAX_TAGS)

          # Convert to JSON array
          TAGS_JSON=$(echo "$TAGS" | jq -R -s 'split("\n")[:-1]')

          echo "Found tags:"
          echo "$TAGS" | while read tag; do
            echo "  - $tag"
          done

          echo "tags=$TAGS_JSON" >> $GITHUB_OUTPUT
          echo "tags-count=$(echo "$TAGS" | wc -l)" >> $GITHUB_OUTPUT

  check-existing-releases:
    runs-on: ubuntu-latest
    needs: get-upstream-tags
    outputs:
      tags-to-build: ${{ steps.filter.outputs.tags-to-build }}
      tags-to-build-count: ${{ steps.filter.outputs.tags-to-build-count }}
    steps:
      - name: Check existing releases
        id: filter
        run: |
          TAGS='${{ needs.get-upstream-tags.outputs.tags }}'
          SKIP_EXISTING="${{ github.event.inputs.skip_existing }}"

          if [ "$SKIP_EXISTING" = "true" ]; then
            echo "Checking existing releases..."
            # Get existing release tags from this repository
            EXISTING_TAGS=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases?per_page=100" | jq -r '.[].tag_name' | sort -V)

            # Filter out existing tags
            TAGS_TO_BUILD=""
            echo "$TAGS" | jq -r '.[]' | while read tag; do
              if echo "$EXISTING_TAGS" | grep -q "^$tag$"; then
                echo "Skipping existing release: $tag"
              else
                echo "Will build: $tag"
                TAGS_TO_BUILD="$TAGS_TO_BUILD$tag"$'\n'
              fi
            done

            # Convert to JSON array
            TAGS_TO_BUILD_JSON=$(echo "$TAGS_TO_BUILD" | jq -R -s 'split("\n")[:-1]')
          else
            echo "Building all tags (not skipping existing)..."
            TAGS_TO_BUILD_JSON="$TAGS"
          fi

          TAGS_TO_BUILD_COUNT=$(echo "$TAGS_TO_BUILD_JSON" | jq 'length')

          echo "tags-to-build=$TAGS_TO_BUILD_JSON" >> $GITHUB_OUTPUT
          echo "tags-to-build-count=$TAGS_TO_BUILD_COUNT" >> $GITHUB_OUTPUT

          echo "Tags to build:"
          echo "$TAGS_TO_BUILD_JSON" | jq -r '.[]' | while read tag; do
            echo "  - $tag"
          done

  build-tags:
    needs: [get-upstream-tags, check-existing-releases]
    if: needs.check-existing-releases.outputs.tags-to-build-count > 0
    runs-on: windows-latest
    strategy:
      matrix:
        tag: ${{ fromJson(needs.check-existing-releases.outputs.tags-to-build) }}
        architecture:
          - ${{ github.event.inputs.build_architectures == 'both' && 'x64' || (github.event.inputs.build_architectures == 'x64-only' && 'x64' || 'x86') }}
          - ${{ github.event.inputs.build_architectures == 'both' && 'x86' || null }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Update ReShade submodule to ${{ matrix.tag }}
        run: |
          cd external/reshade
          git fetch --tags
          git checkout ${{ matrix.tag }}
          cd ../..
          git add external/reshade
          git commit -m "Update ReShade to ${{ matrix.tag }}" || echo "No changes to commit"

      - name: Download Slang binaries
        run: |
          curl -L -o slang.zip https://github.com/shader-slang/slang/releases/download/v2025.10.3/slang-2025.10.3-windows-x86_64.zip
          powershell -Command "Expand-Archive -Path slang.zip -DestinationPath slang_temp -Force; if (!(Test-Path -Path .\bin)) { New-Item -ItemType Directory -Path .\bin }; Copy-Item slang_temp\bin\* .\bin -Force; Remove-Item slang_temp -Recurse -Force"

      - name: Configure CMake (${{ matrix.architecture }})
        run: |
          if [ "${{ matrix.architecture }}" == "x64" ]; then
            cmake --preset vs-x64
          else
            cmake --preset vs-x86
          fi

      - name: Build (${{ matrix.architecture }})
        run: |
          if [ "${{ matrix.architecture }}" == "x64" ]; then
            cmake --build --preset vs-x64-release --verbose
          else
            cmake --build --preset vs-x86-release --verbose
          fi

      - name: Collect build artifacts
        run: |
          $buildDir = if ("${{ matrix.architecture }}" -eq "x86") { "build32.vs" } else { "build.vs" }
          $configDir = "Release"
          $sourceDir = "$buildDir\$configDir"
          $suffix = if ("${{ matrix.architecture }}" -eq "x86") { ".addon32" } else { ".addon64" }

          # Create artifacts directory
          New-Item -ItemType Directory -Path "artifacts" -Force

          # Copy all addon DLLs
          Get-ChildItem -Path $sourceDir -Filter "*$suffix" | ForEach-Object {
            Copy-Item $_.FullName "artifacts\" -Force
            Write-Host "Copied: $($_.Name)"
          }

          # List all artifacts
          Write-Host "Artifacts for ${{ matrix.tag }} (${{ matrix.architecture }}):"
          Get-ChildItem -Path "artifacts" -Filter "*$suffix" | ForEach-Object { Write-Host "  - $($_.Name)" }

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: addons-${{ matrix.architecture }}-${{ matrix.tag }}
          path: artifacts/
          retention-days: 30

  create-releases:
    needs: [get-upstream-tags, check-existing-releases, build-tags]
    if: always() && needs.check-existing-releases.outputs.tags-to-build-count > 0
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ${{ fromJson(needs.check-existing-releases.outputs.tags-to-build) }}

    steps:
      - name: Download artifacts for ${{ matrix.tag }}
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Create release package for ${{ matrix.tag }}
        run: |
          # Create release directory
          mkdir -p release

          # Copy x64 artifacts
          if [ -d "artifacts/addons-x64-${{ matrix.tag }}" ]; then
            cp artifacts/addons-x64-${{ matrix.tag }}/*.addon64 release/ 2>/dev/null || true
            echo "Added x64 artifacts for ${{ matrix.tag }}"
          fi

          # Copy x86 artifacts
          if [ -d "artifacts/addons-x86-${{ matrix.tag }}" ]; then
            cp artifacts/addons-x86-${{ matrix.tag }}/*.addon32 release/ 2>/dev/null || true
            echo "Added x86 artifacts for ${{ matrix.tag }}"
          fi

          # List all files in release
          echo "Release contents for ${{ matrix.tag }}:"
          ls -la release/

          # Create a zip file
          cd release
          zip -r ../renodx2-${{ matrix.tag }}.zip .
          cd ..

          echo "Created release package: renodx2-${{ matrix.tag }}.zip"

      - name: Create GitHub Release for ${{ matrix.tag }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ matrix.tag }}
          name: "ReNoDX2 ${{ matrix.tag }}"
          body: |
            ## ReNoDX2 ${{ matrix.tag }}

            This release is built from upstream ReShade tag ${{ matrix.tag }}.

            ### Included Addons:
            - **x64 versions** (`.addon64`): For 64-bit games
            - **x86 versions** (`.addon32`): For 32-bit games

            ### Installation:
            1. Download the appropriate addon files for your game
            2. Place them in your ReShade addons directory
            3. Configure ReShade to load the addons

            ### Supported Games:
            - Various games with specific addons (see individual addon files)
            - Universal addon (`_univ`) for general compatibility

            ---
            *This is an automated release. For issues, please report them in the repository.*
          files: renodx2-${{ matrix.tag }}.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  summary:
    needs: [get-upstream-tags, check-existing-releases, build-tags, create-releases]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Build Summary
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Total upstream tags found:** ${{ needs.get-upstream-tags.outputs.tags-count }}" >> $GITHUB_STEP_SUMMARY
          echo "**Tags to build:** ${{ needs.check-existing-releases.outputs.tags-to-build-count }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "${{ needs.check-existing-releases.outputs.tags-to-build-count }}" -gt 0 ]; then
            echo "**Tags processed:**" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo '${{ needs.check-existing-releases.outputs.tags-to-build }}' | jq -r '.[]' >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          else
            echo "**No new tags to build** - all selected tags already have releases." >> $GITHUB_STEP_SUMMARY
          fi
