name: Manual Release Build

on:
  workflow_dispatch:
    inputs:
      upstream_tag:
        description: 'Upstream ReShade tag to build (e.g., v6.5.1)'
        required: true
        type: string
      build_architectures:
        description: 'Architectures to build'
        required: true
        type: choice
        options:
          - both
          - x64-only
          - x86-only
        default: both

jobs:
  build-and-release:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - architecture: x64
            condition: ${{ github.event.inputs.build_architectures == 'both' || github.event.inputs.build_architectures == 'x64-only' }}
          - architecture: x86
            condition: ${{ github.event.inputs.build_architectures == 'both' || github.event.inputs.build_architectures == 'x86-only' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Update ReShade submodule to specified tag
        run: |
          cd external/reshade
          git fetch --tags
          git checkout ${{ github.event.inputs.upstream_tag }}
          cd ../..
          git add external/reshade
          git commit -m "Update ReShade to ${{ github.event.inputs.upstream_tag }}" || echo "No changes to commit"

      - name: Download Slang binaries
        run: |
          curl -L -o slang.zip https://github.com/shader-slang/slang/releases/download/v2025.10.3/slang-2025.10.3-windows-x86_64.zip
          powershell -Command "Expand-Archive -Path slang.zip -DestinationPath slang_temp -Force; if (!(Test-Path -Path .\bin)) { New-Item -ItemType Directory -Path .\bin }; Copy-Item slang_temp\bin\* .\bin -Force; Remove-Item slang_temp -Recurse -Force"

      - name: Configure CMake (${{ matrix.architecture }})
        run: |
          if [ "${{ matrix.architecture }}" == "x64" ]; then
            cmake --preset vs-x64
          else
            cmake --preset vs-x86
          fi

      - name: Build (${{ matrix.architecture }})
        run: |
          if [ "${{ matrix.architecture }}" == "x64" ]; then
            cmake --build --preset vs-x64-release --verbose
          else
            cmake --build --preset vs-x86-release --verbose
          fi

      - name: Collect build artifacts
        run: |
          $buildDir = if ("${{ matrix.architecture }}" -eq "x86") { "build32.vs" } else { "build.vs" }
          $configDir = "Release"
          $sourceDir = "$buildDir\$configDir"
          $suffix = if ("${{ matrix.architecture }}" -eq "x86") { ".addon32" } else { ".addon64" }

          # Create artifacts directory
          New-Item -ItemType Directory -Path "artifacts" -Force

          # Copy all addon DLLs
          Get-ChildItem -Path $sourceDir -Filter "*$suffix" | ForEach-Object {
            Copy-Item $_.FullName "artifacts\" -Force
            Write-Host "Copied: $($_.Name)"
          }

          # List all artifacts
          Write-Host "Artifacts for ${{ matrix.architecture }}:"
          Get-ChildItem -Path "artifacts" -Filter "*$suffix" | ForEach-Object { Write-Host "  - $($_.Name)" }

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: addons-${{ matrix.architecture }}-${{ github.event.inputs.upstream_tag }}
          path: artifacts/
          retention-days: 30

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Create release package
        run: |
          # Create release directory
          mkdir -p release

          # Copy x64 artifacts
          if [ -d "artifacts/addons-x64-${{ github.event.inputs.upstream_tag }}" ]; then
            cp artifacts/addons-x64-${{ github.event.inputs.upstream_tag }}/*.addon64 release/ 2>/dev/null || true
            echo "Added x64 artifacts"
          fi

          # Copy x86 artifacts
          if [ -d "artifacts/addons-x86-${{ github.event.inputs.upstream_tag }}" ]; then
            cp artifacts/addons-x86-${{ github.event.inputs.upstream_tag }}/*.addon32 release/ 2>/dev/null || true
            echo "Added x86 artifacts"
          fi

          # List all files in release
          echo "Release contents:"
          ls -la release/

          # Create a zip file
          cd release
          zip -r ../renodx2-${{ github.event.inputs.upstream_tag }}.zip .
          cd ..

          echo "Created release package: renodx2-${{ github.event.inputs.upstream_tag }}.zip"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.upstream_tag }}
          name: "ReNoDX2 ${{ github.event.inputs.upstream_tag }}"
          body: |
            ## ReNoDX2 ${{ github.event.inputs.upstream_tag }}

            This release is built from upstream ReShade tag ${{ github.event.inputs.upstream_tag }}.

            ### Included Addons:
            - **x64 versions** (`.addon64`): For 64-bit games
            - **x86 versions** (`.addon32`): For 32-bit games

            ### Installation:
            1. Download the appropriate addon files for your game
            2. Place them in your ReShade addons directory
            3. Configure ReShade to load the addons

            ### Supported Games:
            - Various games with specific addons (see individual addon files)
            - Universal addon (`_univ`) for general compatibility

            ---
            *This is a manual release build. For issues, please report them in the repository.*
          files: renodx2-${{ github.event.inputs.upstream_tag }}.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
